### ISSUE TITLE
Encounter ParseCancellationException with filer=i*

### ISSUE THREAD

**Issue by maxliu007** [bohnman/squiggly#73]
When I tried to select fields with wildcard like that "fields=i*",  I encountered error.
**There is no problem when I tried to use other filters, like id*, h* and c* but not i*.**
Here is the simplified code:
```
public class Test {

	public static void main(String[] args) {
		String filter = "i*";
		ObjectMapper mapper = Squiggly.init(new ObjectMapper(), filter);
		TxnRes res = new TxnRes();
		res.setId("123");
		System.out.println(SquigglyUtils.stringify(mapper, res));
	}
	
	@NoArgsConstructor
	@Data
	static public class TxnRes {
		private String id;
		private String holderId;
		private String current;
	}

}
```

Here is the error:
```
Caused by: org.antlr.v4.runtime.misc.ParseCancellationException: line 1:0 extraneous input 'i' expecting {'(', '-', '~', '/', '?', IDENTIFIER, '*', '**'}
	at com.github.bohnman.squiggly.util.antlr4.ThrowingErrorListener.syntaxError(ThrowingErrorListener.java:14)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:540)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:351)
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:515)
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:240)
	at com.github.bohnman.squiggly.parser.antlr4.SquigglyExpressionParser.expression(SquigglyExpressionParser.java:251)
	at com.github.bohnman.squiggly.parser.antlr4.SquigglyExpressionParser.expression_list(SquigglyExpressionParser.java:175)
	at com.github.bohnman.squiggly.parser.antlr4.SquigglyExpressionParser.parse(SquigglyExpressionParser.java:125)
	at com.github.bohnman.squiggly.parser.SquigglyParser.parse(SquigglyParser.java:62)
	at com.github.bohnman.squiggly.context.LazySquigglyContext.getNodes(LazySquigglyContext.java:34)
	at com.github.bohnman.squiggly.filter.SquigglyPropertyFilter.pathMatches(SquigglyPropertyFilter.java:181)
	at com.github.bohnman.squiggly.filter.SquigglyPropertyFilter.include(SquigglyPropertyFilter.java:169)
	at com.github.bohnman.squiggly.filter.SquigglyPropertyFilter.serializeAsField(SquigglyPropertyFilter.java:338)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFieldsFiltered(BeanSerializerBase.java:773)
	... 7 more
```

**Comment by maxliu007** [comment]
Provided that I am using :
	<dependency>
            <groupId>com.github.bohnman</groupId>
            <artifactId>squiggly-filter-jackson</artifactId>
            <version>1.3.18</version>
        </dependency>

**Comment by bohnman** [comment]
I found the cause.  I'm currently pondering the proper fix.
