### ISSUE TITLE
ParseCancellationException with filer by field name with @

### ISSUE THREAD

**Issue by Lolret** [bohnman/squiggly#84]
POJO
```
class Resource {
     @JsonProperty("@type")
    private String atType;

    private String resourceCharacteristic;
}
```

Code:
```
        filter="@type";
        ObjectMapper squigglyMapper = Squiggly.init(objectMapper, filter);
        List<Resource> resources = resourceService.getResources();
        resources = SquigglyUtils.listify(squigglyMapper, resources, Resource.class);
```

Error:
```
org.antlr.v4.runtime.misc.ParseCancellationException: line 1:23 extraneous input '@' expecting {'(', '-', '~', '/', '?', IDENTIFIER, '*', '**'}
	at com.github.bohnman.squiggly.util.antlr4.ThrowingErrorListener.syntaxError(ThrowingErrorListener.java:14) ~[squiggly-filter-jackson-1.3.18.jar:na]
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41) ~[antlr4-runtime-4.6.jar:4.6]
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:540) ~[antlr4-runtime-4.6.jar:4.6]
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:351) ~[antlr4-runtime-4.6.jar:4.6]
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:515) ~[antlr4-runtime-4.6.jar:4.6]
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:240) ~[antlr4-runtime-4.6.jar:4.6]
	at com.github.bohnman.squiggly.parser.antlr4.SquigglyExpressionParser.expression(SquigglyExpressionParser.java:251) ~[squiggly-filter-jackson-1.3.18.jar:na]
	at com.github.bohnman.squiggly.parser.antlr4.SquigglyExpressionParser.expression_list(SquigglyExpressionParser.java:185) ~[squiggly-filter-jackson-1.3.18.jar:na]
	at com.github.bohnman.squiggly.parser.antlr4.SquigglyExpressionParser.parse(SquigglyExpressionParser.java:125) ~[squiggly-filter-jackson-1.3.18.jar:na]
	at com.github.bohnman.squiggly.parser.SquigglyParser.parse(SquigglyParser.java:62) ~[squiggly-filter-jackson-1.3.18.jar:na]
	at com.github.bohnman.squiggly.context.LazySquigglyContext.getNodes(LazySquigglyContext.java:34) ~[squiggly-filter-jackson-1.3.18.jar:na]
	at com.github.bohnman.squiggly.filter.SquigglyPropertyFilter.pathMatches(SquigglyPropertyFilter.java:181) ~[squiggly-filter-jackson-1.3.18.jar:na]
	at com.github.bohnman.squiggly.filter.SquigglyPropertyFilter.include(SquigglyPropertyFilter.java:169) ~[squiggly-filter-jackson-1.3.18.jar:na]
	at com.github.bohnman.squiggly.filter.SquigglyPropertyFilter.serializeAsField(SquigglyPropertyFilter.java:338) ~[squiggly-filter-jackson-1.3.18.jar:na]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFieldsFiltered(BeanSerializerBase.java:774) ~[jackson-databind-2.10.3.jar:2.10.3]

```

pom.xml

```
        <dependency>
            <groupId>com.github.bohnman</groupId>
            <artifactId>squiggly-filter-jackson</artifactId>
            <version>1.3.18</version>
        </dependency>
```

**Comment by chicobento** [comment]
Sorry, I know its an old issue, but I'll leave a workaround for future visitors.
The cause seems to be the limitation with the chars supported in field names: https://github.com/bohnman/squiggly/blob/78598ffffeebeb8536c6056de0e77ab463abbdb1/src/main/antlr4/com/github/bohnman/squiggly/parser/antlr4/SquigglyExpression.g4#L102

So if you treat the filter as a regex it should work. Something like:

`filter="~\@type~";`
